// =====================================================================
// masked_aes_round1_second_order.v
// =====================================================================
// Single-round masked AES-128 (Boolean masking, d=2, share count = 3).
// Generated by gen_masked_aes_round1_d2.py; do not edit by hand.
//
// Round 1 = SubBytes + ShiftRows + MixColumns + AddRoundKey.
//   - SubBytes: 16 parallel masked_sbox_second_order instances
//   - ShiftRows, MixColumns: combinational share-wise (linear GF(2^8))
//   - AddRoundKey, output register: clocked
//
// AES state packing: 128-bit bus, byte index = row + 4*col (column-major).
//   Byte 0 is (row 0, col 0), byte 4 is (row 0, col 1), ..., byte 15
//   is (row 3, col 3).
//
// Key schedule is performed OFF-LINE; the round key is supplied as
// three shares (rk0, rk1, rk2) where rk0 ^ rk1 ^ rk2 = the actual
// round key.
//
// Latency: 10 cycles (S-box pipeline) + 1 (ARK register) +
//          1 (output register) = 12 cycles.  valid_out is
//          combinational from sb_v_all.
//
// Randomness budget per round: 16 S-boxes * 63 bytes = 1008 bytes
//                              = 8064 fresh bits per AES round.
// =====================================================================

`timescale 1ns/1ps

module masked_aes_round1_second_order (
    input              clk,
    input              rst_n,
    input              valid_in,

    // ----- 16-byte plaintext (three shares) -----
    input  [127:0]     x0_in,
    input  [127:0]     x1_in,
    input  [127:0]     x2_in,

    // ----- 16-byte round key (three shares) -----
    input  [127:0]     rk0_in,
    input  [127:0]     rk1_in,
    input  [127:0]     rk2_in,

    // ----- 1008 mask bytes (16 S-boxes * 63 bytes each) -----
    input  [7:0] r000_in, r001_in, r002_in, r003_in, r004_in, r005_in, r006_in, r007_in,
    input  [7:0] r008_in, r009_in, r010_in, r011_in, r012_in, r013_in, r014_in, r015_in,
    input  [7:0] r016_in, r017_in, r018_in, r019_in, r020_in, r021_in, r022_in, r023_in,
    input  [7:0] r024_in, r025_in, r026_in, r027_in, r028_in, r029_in, r030_in, r031_in,
    input  [7:0] r032_in, r033_in, r034_in, r035_in, r036_in, r037_in, r038_in, r039_in,
    input  [7:0] r040_in, r041_in, r042_in, r043_in, r044_in, r045_in, r046_in, r047_in,
    input  [7:0] r048_in, r049_in, r050_in, r051_in, r052_in, r053_in, r054_in, r055_in,
    input  [7:0] r056_in, r057_in, r058_in, r059_in, r060_in, r061_in, r062_in, r063_in,
    input  [7:0] r064_in, r065_in, r066_in, r067_in, r068_in, r069_in, r070_in, r071_in,
    input  [7:0] r072_in, r073_in, r074_in, r075_in, r076_in, r077_in, r078_in, r079_in,
    input  [7:0] r080_in, r081_in, r082_in, r083_in, r084_in, r085_in, r086_in, r087_in,
    input  [7:0] r088_in, r089_in, r090_in, r091_in, r092_in, r093_in, r094_in, r095_in,
    input  [7:0] r096_in, r097_in, r098_in, r099_in, r100_in, r101_in, r102_in, r103_in,
    input  [7:0] r104_in, r105_in, r106_in, r107_in, r108_in, r109_in, r110_in, r111_in,
    input  [7:0] r112_in, r113_in, r114_in, r115_in, r116_in, r117_in, r118_in, r119_in,
    input  [7:0] r120_in, r121_in, r122_in, r123_in, r124_in, r125_in, r126_in, r127_in,
    input  [7:0] r128_in, r129_in, r130_in, r131_in, r132_in, r133_in, r134_in, r135_in,
    input  [7:0] r136_in, r137_in, r138_in, r139_in, r140_in, r141_in, r142_in, r143_in,
    input  [7:0] r144_in, r145_in, r146_in, r147_in, r148_in, r149_in, r150_in, r151_in,
    input  [7:0] r152_in, r153_in, r154_in, r155_in, r156_in, r157_in, r158_in, r159_in,
    input  [7:0] r160_in, r161_in, r162_in, r163_in, r164_in, r165_in, r166_in, r167_in,
    input  [7:0] r168_in, r169_in, r170_in, r171_in, r172_in, r173_in, r174_in, r175_in,
    input  [7:0] r176_in, r177_in, r178_in, r179_in, r180_in, r181_in, r182_in, r183_in,
    input  [7:0] r184_in, r185_in, r186_in, r187_in, r188_in, r189_in, r190_in, r191_in,
    input  [7:0] r192_in, r193_in, r194_in, r195_in, r196_in, r197_in, r198_in, r199_in,
    input  [7:0] r200_in, r201_in, r202_in, r203_in, r204_in, r205_in, r206_in, r207_in,
    input  [7:0] r208_in, r209_in, r210_in, r211_in, r212_in, r213_in, r214_in, r215_in,
    input  [7:0] r216_in, r217_in, r218_in, r219_in, r220_in, r221_in, r222_in, r223_in,
    input  [7:0] r224_in, r225_in, r226_in, r227_in, r228_in, r229_in, r230_in, r231_in,
    input  [7:0] r232_in, r233_in, r234_in, r235_in, r236_in, r237_in, r238_in, r239_in,
    input  [7:0] r240_in, r241_in, r242_in, r243_in, r244_in, r245_in, r246_in, r247_in,
    input  [7:0] r248_in, r249_in, r250_in, r251_in, r252_in, r253_in, r254_in, r255_in,
    input  [7:0] r256_in, r257_in, r258_in, r259_in, r260_in, r261_in, r262_in, r263_in,
    input  [7:0] r264_in, r265_in, r266_in, r267_in, r268_in, r269_in, r270_in, r271_in,
    input  [7:0] r272_in, r273_in, r274_in, r275_in, r276_in, r277_in, r278_in, r279_in,
    input  [7:0] r280_in, r281_in, r282_in, r283_in, r284_in, r285_in, r286_in, r287_in,
    input  [7:0] r288_in, r289_in, r290_in, r291_in, r292_in, r293_in, r294_in, r295_in,
    input  [7:0] r296_in, r297_in, r298_in, r299_in, r300_in, r301_in, r302_in, r303_in,
    input  [7:0] r304_in, r305_in, r306_in, r307_in, r308_in, r309_in, r310_in, r311_in,
    input  [7:0] r312_in, r313_in, r314_in, r315_in, r316_in, r317_in, r318_in, r319_in,
    input  [7:0] r320_in, r321_in, r322_in, r323_in, r324_in, r325_in, r326_in, r327_in,
    input  [7:0] r328_in, r329_in, r330_in, r331_in, r332_in, r333_in, r334_in, r335_in,
    input  [7:0] r336_in, r337_in, r338_in, r339_in, r340_in, r341_in, r342_in, r343_in,
    input  [7:0] r344_in, r345_in, r346_in, r347_in, r348_in, r349_in, r350_in, r351_in,
    input  [7:0] r352_in, r353_in, r354_in, r355_in, r356_in, r357_in, r358_in, r359_in,
    input  [7:0] r360_in, r361_in, r362_in, r363_in, r364_in, r365_in, r366_in, r367_in,
    input  [7:0] r368_in, r369_in, r370_in, r371_in, r372_in, r373_in, r374_in, r375_in,
    input  [7:0] r376_in, r377_in, r378_in, r379_in, r380_in, r381_in, r382_in, r383_in,
    input  [7:0] r384_in, r385_in, r386_in, r387_in, r388_in, r389_in, r390_in, r391_in,
    input  [7:0] r392_in, r393_in, r394_in, r395_in, r396_in, r397_in, r398_in, r399_in,
    input  [7:0] r400_in, r401_in, r402_in, r403_in, r404_in, r405_in, r406_in, r407_in,
    input  [7:0] r408_in, r409_in, r410_in, r411_in, r412_in, r413_in, r414_in, r415_in,
    input  [7:0] r416_in, r417_in, r418_in, r419_in, r420_in, r421_in, r422_in, r423_in,
    input  [7:0] r424_in, r425_in, r426_in, r427_in, r428_in, r429_in, r430_in, r431_in,
    input  [7:0] r432_in, r433_in, r434_in, r435_in, r436_in, r437_in, r438_in, r439_in,
    input  [7:0] r440_in, r441_in, r442_in, r443_in, r444_in, r445_in, r446_in, r447_in,
    input  [7:0] r448_in, r449_in, r450_in, r451_in, r452_in, r453_in, r454_in, r455_in,
    input  [7:0] r456_in, r457_in, r458_in, r459_in, r460_in, r461_in, r462_in, r463_in,
    input  [7:0] r464_in, r465_in, r466_in, r467_in, r468_in, r469_in, r470_in, r471_in,
    input  [7:0] r472_in, r473_in, r474_in, r475_in, r476_in, r477_in, r478_in, r479_in,
    input  [7:0] r480_in, r481_in, r482_in, r483_in, r484_in, r485_in, r486_in, r487_in,
    input  [7:0] r488_in, r489_in, r490_in, r491_in, r492_in, r493_in, r494_in, r495_in,
    input  [7:0] r496_in, r497_in, r498_in, r499_in, r500_in, r501_in, r502_in, r503_in,
    input  [7:0] r504_in, r505_in, r506_in, r507_in, r508_in, r509_in, r510_in, r511_in,
    input  [7:0] r512_in, r513_in, r514_in, r515_in, r516_in, r517_in, r518_in, r519_in,
    input  [7:0] r520_in, r521_in, r522_in, r523_in, r524_in, r525_in, r526_in, r527_in,
    input  [7:0] r528_in, r529_in, r530_in, r531_in, r532_in, r533_in, r534_in, r535_in,
    input  [7:0] r536_in, r537_in, r538_in, r539_in, r540_in, r541_in, r542_in, r543_in,
    input  [7:0] r544_in, r545_in, r546_in, r547_in, r548_in, r549_in, r550_in, r551_in,
    input  [7:0] r552_in, r553_in, r554_in, r555_in, r556_in, r557_in, r558_in, r559_in,
    input  [7:0] r560_in, r561_in, r562_in, r563_in, r564_in, r565_in, r566_in, r567_in,
    input  [7:0] r568_in, r569_in, r570_in, r571_in, r572_in, r573_in, r574_in, r575_in,
    input  [7:0] r576_in, r577_in, r578_in, r579_in, r580_in, r581_in, r582_in, r583_in,
    input  [7:0] r584_in, r585_in, r586_in, r587_in, r588_in, r589_in, r590_in, r591_in,
    input  [7:0] r592_in, r593_in, r594_in, r595_in, r596_in, r597_in, r598_in, r599_in,
    input  [7:0] r600_in, r601_in, r602_in, r603_in, r604_in, r605_in, r606_in, r607_in,
    input  [7:0] r608_in, r609_in, r610_in, r611_in, r612_in, r613_in, r614_in, r615_in,
    input  [7:0] r616_in, r617_in, r618_in, r619_in, r620_in, r621_in, r622_in, r623_in,
    input  [7:0] r624_in, r625_in, r626_in, r627_in, r628_in, r629_in, r630_in, r631_in,
    input  [7:0] r632_in, r633_in, r634_in, r635_in, r636_in, r637_in, r638_in, r639_in,
    input  [7:0] r640_in, r641_in, r642_in, r643_in, r644_in, r645_in, r646_in, r647_in,
    input  [7:0] r648_in, r649_in, r650_in, r651_in, r652_in, r653_in, r654_in, r655_in,
    input  [7:0] r656_in, r657_in, r658_in, r659_in, r660_in, r661_in, r662_in, r663_in,
    input  [7:0] r664_in, r665_in, r666_in, r667_in, r668_in, r669_in, r670_in, r671_in,
    input  [7:0] r672_in, r673_in, r674_in, r675_in, r676_in, r677_in, r678_in, r679_in,
    input  [7:0] r680_in, r681_in, r682_in, r683_in, r684_in, r685_in, r686_in, r687_in,
    input  [7:0] r688_in, r689_in, r690_in, r691_in, r692_in, r693_in, r694_in, r695_in,
    input  [7:0] r696_in, r697_in, r698_in, r699_in, r700_in, r701_in, r702_in, r703_in,
    input  [7:0] r704_in, r705_in, r706_in, r707_in, r708_in, r709_in, r710_in, r711_in,
    input  [7:0] r712_in, r713_in, r714_in, r715_in, r716_in, r717_in, r718_in, r719_in,
    input  [7:0] r720_in, r721_in, r722_in, r723_in, r724_in, r725_in, r726_in, r727_in,
    input  [7:0] r728_in, r729_in, r730_in, r731_in, r732_in, r733_in, r734_in, r735_in,
    input  [7:0] r736_in, r737_in, r738_in, r739_in, r740_in, r741_in, r742_in, r743_in,
    input  [7:0] r744_in, r745_in, r746_in, r747_in, r748_in, r749_in, r750_in, r751_in,
    input  [7:0] r752_in, r753_in, r754_in, r755_in, r756_in, r757_in, r758_in, r759_in,
    input  [7:0] r760_in, r761_in, r762_in, r763_in, r764_in, r765_in, r766_in, r767_in,
    input  [7:0] r768_in, r769_in, r770_in, r771_in, r772_in, r773_in, r774_in, r775_in,
    input  [7:0] r776_in, r777_in, r778_in, r779_in, r780_in, r781_in, r782_in, r783_in,
    input  [7:0] r784_in, r785_in, r786_in, r787_in, r788_in, r789_in, r790_in, r791_in,
    input  [7:0] r792_in, r793_in, r794_in, r795_in, r796_in, r797_in, r798_in, r799_in,
    input  [7:0] r800_in, r801_in, r802_in, r803_in, r804_in, r805_in, r806_in, r807_in,
    input  [7:0] r808_in, r809_in, r810_in, r811_in, r812_in, r813_in, r814_in, r815_in,
    input  [7:0] r816_in, r817_in, r818_in, r819_in, r820_in, r821_in, r822_in, r823_in,
    input  [7:0] r824_in, r825_in, r826_in, r827_in, r828_in, r829_in, r830_in, r831_in,
    input  [7:0] r832_in, r833_in, r834_in, r835_in, r836_in, r837_in, r838_in, r839_in,
    input  [7:0] r840_in, r841_in, r842_in, r843_in, r844_in, r845_in, r846_in, r847_in,
    input  [7:0] r848_in, r849_in, r850_in, r851_in, r852_in, r853_in, r854_in, r855_in,
    input  [7:0] r856_in, r857_in, r858_in, r859_in, r860_in, r861_in, r862_in, r863_in,
    input  [7:0] r864_in, r865_in, r866_in, r867_in, r868_in, r869_in, r870_in, r871_in,
    input  [7:0] r872_in, r873_in, r874_in, r875_in, r876_in, r877_in, r878_in, r879_in,
    input  [7:0] r880_in, r881_in, r882_in, r883_in, r884_in, r885_in, r886_in, r887_in,
    input  [7:0] r888_in, r889_in, r890_in, r891_in, r892_in, r893_in, r894_in, r895_in,
    input  [7:0] r896_in, r897_in, r898_in, r899_in, r900_in, r901_in, r902_in, r903_in,
    input  [7:0] r904_in, r905_in, r906_in, r907_in, r908_in, r909_in, r910_in, r911_in,
    input  [7:0] r912_in, r913_in, r914_in, r915_in, r916_in, r917_in, r918_in, r919_in,
    input  [7:0] r920_in, r921_in, r922_in, r923_in, r924_in, r925_in, r926_in, r927_in,
    input  [7:0] r928_in, r929_in, r930_in, r931_in, r932_in, r933_in, r934_in, r935_in,
    input  [7:0] r936_in, r937_in, r938_in, r939_in, r940_in, r941_in, r942_in, r943_in,
    input  [7:0] r944_in, r945_in, r946_in, r947_in, r948_in, r949_in, r950_in, r951_in,
    input  [7:0] r952_in, r953_in, r954_in, r955_in, r956_in, r957_in, r958_in, r959_in,
    input  [7:0] r960_in, r961_in, r962_in, r963_in, r964_in, r965_in, r966_in, r967_in,
    input  [7:0] r968_in, r969_in, r970_in, r971_in, r972_in, r973_in, r974_in, r975_in,
    input  [7:0] r976_in, r977_in, r978_in, r979_in, r980_in, r981_in, r982_in, r983_in,
    input  [7:0] r984_in, r985_in, r986_in, r987_in, r988_in, r989_in, r990_in, r991_in,
    input  [7:0] r992_in, r993_in, r994_in, r995_in, r996_in, r997_in, r998_in, r999_in,
    input  [7:0] r1000_in, r1001_in, r1002_in, r1003_in, r1004_in, r1005_in, r1006_in, r1007_in,
    // ----- Output -----
    output             valid_out,
    output reg [127:0] y0_out,
    output reg [127:0] y1_out,
    output reg [127:0] y2_out
);

    // ----------------------------------------------------------------
    // xtime (forward declaration so ShiftRows/MixColumns below can use it)
    // ----------------------------------------------------------------
    function [7:0] xtime_f;
        input [7:0] b;
        reg [7:0] t;
        begin
            t = {b[6:0], 1'b0};
            xtime_f = b[7] ? (t ^ 8'h1b) : t;
        end
    endfunction

    // ----------------------------------------------------------------
    // STAGE 1: SubBytes (16 parallel masked S-boxes)
    // ----------------------------------------------------------------
    wire        sb_v   [0:15];
    wire [7:0]  sb_y0  [0:15];
    wire [7:0]  sb_y1  [0:15];
    wire [7:0]  sb_y2  [0:15];

    // Pack S-box outputs into 128-bit buses.  sb_y{k}[i] holds the
    // S-box output share k for state byte i, placed at bit-slice
    // [8*i+:8].
    wire [127:0] sb_state_y0 = {sb_y0[15], sb_y0[14], sb_y0[13], sb_y0[12], sb_y0[11], sb_y0[10], sb_y0[ 9], sb_y0[ 8], sb_y0[ 7], sb_y0[ 6], sb_y0[ 5], sb_y0[ 4], sb_y0[ 3], sb_y0[ 2], sb_y0[ 1], sb_y0[ 0]};
    wire [127:0] sb_state_y1 = {sb_y1[15], sb_y1[14], sb_y1[13], sb_y1[12], sb_y1[11], sb_y1[10], sb_y1[ 9], sb_y1[ 8], sb_y1[ 7], sb_y1[ 6], sb_y1[ 5], sb_y1[ 4], sb_y1[ 3], sb_y1[ 2], sb_y1[ 1], sb_y1[ 0]};
    wire [127:0] sb_state_y2 = {sb_y2[15], sb_y2[14], sb_y2[13], sb_y2[12], sb_y2[11], sb_y2[10], sb_y2[ 9], sb_y2[ 8], sb_y2[ 7], sb_y2[ 6], sb_y2[ 5], sb_y2[ 4], sb_y2[ 3], sb_y2[ 2], sb_y2[ 1], sb_y2[ 0]};

    masked_sbox_second_order u_sbox_0 (
        .clk(clk), .rst_n(rst_n), .valid_in(valid_in),
        .x0_in(x0_in[  0 +: 8]), .x1_in(x1_in[  0 +: 8]), .x2_in(x2_in[  0 +: 8]),
        .r00(r000_in), .r01(r001_in), .r02(r002_in), .r03(r003_in), .r04(r004_in), .r05(r005_in), .r06(r006_in), .r07(r007_in), .r08(r008_in), .r09(r009_in), .r10(r010_in), .r11(r011_in), .r12(r012_in), .r13(r013_in), .r14(r014_in), .r15(r015_in), .r16(r016_in), .r17(r017_in), .r18(r018_in), .r19(r019_in), .r20(r020_in), .r21(r021_in), .r22(r022_in), .r23(r023_in), .r24(r024_in), .r25(r025_in), .r26(r026_in), .r27(r027_in), .r28(r028_in), .r29(r029_in), .r30(r030_in), .r31(r031_in), .r32(r032_in), .r33(r033_in), .r34(r034_in), .r35(r035_in), .r36(r036_in), .r37(r037_in), .r38(r038_in), .r39(r039_in), .r40(r040_in), .r41(r041_in), .r42(r042_in), .r43(r043_in), .r44(r044_in), .r45(r045_in), .r46(r046_in), .r47(r047_in), .r48(r048_in), .r49(r049_in), .r50(r050_in), .r51(r051_in), .r52(r052_in), .r53(r053_in), .r54(r054_in), .r55(r055_in), .r56(r056_in), .r57(r057_in), .r58(r058_in), .r59(r059_in), .r60(r060_in), .r61(r061_in), .r62(r062_in),
        .valid_out(sb_v[ 0]), .y0_out(sb_y0[ 0]), .y1_out(sb_y1[ 0]), .y2_out(sb_y2[ 0]));
    masked_sbox_second_order u_sbox_1 (
        .clk(clk), .rst_n(rst_n), .valid_in(valid_in),
        .x0_in(x0_in[  8 +: 8]), .x1_in(x1_in[  8 +: 8]), .x2_in(x2_in[  8 +: 8]),
        .r00(r063_in), .r01(r064_in), .r02(r065_in), .r03(r066_in), .r04(r067_in), .r05(r068_in), .r06(r069_in), .r07(r070_in), .r08(r071_in), .r09(r072_in), .r10(r073_in), .r11(r074_in), .r12(r075_in), .r13(r076_in), .r14(r077_in), .r15(r078_in), .r16(r079_in), .r17(r080_in), .r18(r081_in), .r19(r082_in), .r20(r083_in), .r21(r084_in), .r22(r085_in), .r23(r086_in), .r24(r087_in), .r25(r088_in), .r26(r089_in), .r27(r090_in), .r28(r091_in), .r29(r092_in), .r30(r093_in), .r31(r094_in), .r32(r095_in), .r33(r096_in), .r34(r097_in), .r35(r098_in), .r36(r099_in), .r37(r100_in), .r38(r101_in), .r39(r102_in), .r40(r103_in), .r41(r104_in), .r42(r105_in), .r43(r106_in), .r44(r107_in), .r45(r108_in), .r46(r109_in), .r47(r110_in), .r48(r111_in), .r49(r112_in), .r50(r113_in), .r51(r114_in), .r52(r115_in), .r53(r116_in), .r54(r117_in), .r55(r118_in), .r56(r119_in), .r57(r120_in), .r58(r121_in), .r59(r122_in), .r60(r123_in), .r61(r124_in), .r62(r125_in),
        .valid_out(sb_v[ 1]), .y0_out(sb_y0[ 1]), .y1_out(sb_y1[ 1]), .y2_out(sb_y2[ 1]));
    masked_sbox_second_order u_sbox_2 (
        .clk(clk), .rst_n(rst_n), .valid_in(valid_in),
        .x0_in(x0_in[ 16 +: 8]), .x1_in(x1_in[ 16 +: 8]), .x2_in(x2_in[ 16 +: 8]),
        .r00(r126_in), .r01(r127_in), .r02(r128_in), .r03(r129_in), .r04(r130_in), .r05(r131_in), .r06(r132_in), .r07(r133_in), .r08(r134_in), .r09(r135_in), .r10(r136_in), .r11(r137_in), .r12(r138_in), .r13(r139_in), .r14(r140_in), .r15(r141_in), .r16(r142_in), .r17(r143_in), .r18(r144_in), .r19(r145_in), .r20(r146_in), .r21(r147_in), .r22(r148_in), .r23(r149_in), .r24(r150_in), .r25(r151_in), .r26(r152_in), .r27(r153_in), .r28(r154_in), .r29(r155_in), .r30(r156_in), .r31(r157_in), .r32(r158_in), .r33(r159_in), .r34(r160_in), .r35(r161_in), .r36(r162_in), .r37(r163_in), .r38(r164_in), .r39(r165_in), .r40(r166_in), .r41(r167_in), .r42(r168_in), .r43(r169_in), .r44(r170_in), .r45(r171_in), .r46(r172_in), .r47(r173_in), .r48(r174_in), .r49(r175_in), .r50(r176_in), .r51(r177_in), .r52(r178_in), .r53(r179_in), .r54(r180_in), .r55(r181_in), .r56(r182_in), .r57(r183_in), .r58(r184_in), .r59(r185_in), .r60(r186_in), .r61(r187_in), .r62(r188_in),
        .valid_out(sb_v[ 2]), .y0_out(sb_y0[ 2]), .y1_out(sb_y1[ 2]), .y2_out(sb_y2[ 2]));
    masked_sbox_second_order u_sbox_3 (
        .clk(clk), .rst_n(rst_n), .valid_in(valid_in),
        .x0_in(x0_in[ 24 +: 8]), .x1_in(x1_in[ 24 +: 8]), .x2_in(x2_in[ 24 +: 8]),
        .r00(r189_in), .r01(r190_in), .r02(r191_in), .r03(r192_in), .r04(r193_in), .r05(r194_in), .r06(r195_in), .r07(r196_in), .r08(r197_in), .r09(r198_in), .r10(r199_in), .r11(r200_in), .r12(r201_in), .r13(r202_in), .r14(r203_in), .r15(r204_in), .r16(r205_in), .r17(r206_in), .r18(r207_in), .r19(r208_in), .r20(r209_in), .r21(r210_in), .r22(r211_in), .r23(r212_in), .r24(r213_in), .r25(r214_in), .r26(r215_in), .r27(r216_in), .r28(r217_in), .r29(r218_in), .r30(r219_in), .r31(r220_in), .r32(r221_in), .r33(r222_in), .r34(r223_in), .r35(r224_in), .r36(r225_in), .r37(r226_in), .r38(r227_in), .r39(r228_in), .r40(r229_in), .r41(r230_in), .r42(r231_in), .r43(r232_in), .r44(r233_in), .r45(r234_in), .r46(r235_in), .r47(r236_in), .r48(r237_in), .r49(r238_in), .r50(r239_in), .r51(r240_in), .r52(r241_in), .r53(r242_in), .r54(r243_in), .r55(r244_in), .r56(r245_in), .r57(r246_in), .r58(r247_in), .r59(r248_in), .r60(r249_in), .r61(r250_in), .r62(r251_in),
        .valid_out(sb_v[ 3]), .y0_out(sb_y0[ 3]), .y1_out(sb_y1[ 3]), .y2_out(sb_y2[ 3]));
    masked_sbox_second_order u_sbox_4 (
        .clk(clk), .rst_n(rst_n), .valid_in(valid_in),
        .x0_in(x0_in[ 32 +: 8]), .x1_in(x1_in[ 32 +: 8]), .x2_in(x2_in[ 32 +: 8]),
        .r00(r252_in), .r01(r253_in), .r02(r254_in), .r03(r255_in), .r04(r256_in), .r05(r257_in), .r06(r258_in), .r07(r259_in), .r08(r260_in), .r09(r261_in), .r10(r262_in), .r11(r263_in), .r12(r264_in), .r13(r265_in), .r14(r266_in), .r15(r267_in), .r16(r268_in), .r17(r269_in), .r18(r270_in), .r19(r271_in), .r20(r272_in), .r21(r273_in), .r22(r274_in), .r23(r275_in), .r24(r276_in), .r25(r277_in), .r26(r278_in), .r27(r279_in), .r28(r280_in), .r29(r281_in), .r30(r282_in), .r31(r283_in), .r32(r284_in), .r33(r285_in), .r34(r286_in), .r35(r287_in), .r36(r288_in), .r37(r289_in), .r38(r290_in), .r39(r291_in), .r40(r292_in), .r41(r293_in), .r42(r294_in), .r43(r295_in), .r44(r296_in), .r45(r297_in), .r46(r298_in), .r47(r299_in), .r48(r300_in), .r49(r301_in), .r50(r302_in), .r51(r303_in), .r52(r304_in), .r53(r305_in), .r54(r306_in), .r55(r307_in), .r56(r308_in), .r57(r309_in), .r58(r310_in), .r59(r311_in), .r60(r312_in), .r61(r313_in), .r62(r314_in),
        .valid_out(sb_v[ 4]), .y0_out(sb_y0[ 4]), .y1_out(sb_y1[ 4]), .y2_out(sb_y2[ 4]));
    masked_sbox_second_order u_sbox_5 (
        .clk(clk), .rst_n(rst_n), .valid_in(valid_in),
        .x0_in(x0_in[ 40 +: 8]), .x1_in(x1_in[ 40 +: 8]), .x2_in(x2_in[ 40 +: 8]),
        .r00(r315_in), .r01(r316_in), .r02(r317_in), .r03(r318_in), .r04(r319_in), .r05(r320_in), .r06(r321_in), .r07(r322_in), .r08(r323_in), .r09(r324_in), .r10(r325_in), .r11(r326_in), .r12(r327_in), .r13(r328_in), .r14(r329_in), .r15(r330_in), .r16(r331_in), .r17(r332_in), .r18(r333_in), .r19(r334_in), .r20(r335_in), .r21(r336_in), .r22(r337_in), .r23(r338_in), .r24(r339_in), .r25(r340_in), .r26(r341_in), .r27(r342_in), .r28(r343_in), .r29(r344_in), .r30(r345_in), .r31(r346_in), .r32(r347_in), .r33(r348_in), .r34(r349_in), .r35(r350_in), .r36(r351_in), .r37(r352_in), .r38(r353_in), .r39(r354_in), .r40(r355_in), .r41(r356_in), .r42(r357_in), .r43(r358_in), .r44(r359_in), .r45(r360_in), .r46(r361_in), .r47(r362_in), .r48(r363_in), .r49(r364_in), .r50(r365_in), .r51(r366_in), .r52(r367_in), .r53(r368_in), .r54(r369_in), .r55(r370_in), .r56(r371_in), .r57(r372_in), .r58(r373_in), .r59(r374_in), .r60(r375_in), .r61(r376_in), .r62(r377_in),
        .valid_out(sb_v[ 5]), .y0_out(sb_y0[ 5]), .y1_out(sb_y1[ 5]), .y2_out(sb_y2[ 5]));
    masked_sbox_second_order u_sbox_6 (
        .clk(clk), .rst_n(rst_n), .valid_in(valid_in),
        .x0_in(x0_in[ 48 +: 8]), .x1_in(x1_in[ 48 +: 8]), .x2_in(x2_in[ 48 +: 8]),
        .r00(r378_in), .r01(r379_in), .r02(r380_in), .r03(r381_in), .r04(r382_in), .r05(r383_in), .r06(r384_in), .r07(r385_in), .r08(r386_in), .r09(r387_in), .r10(r388_in), .r11(r389_in), .r12(r390_in), .r13(r391_in), .r14(r392_in), .r15(r393_in), .r16(r394_in), .r17(r395_in), .r18(r396_in), .r19(r397_in), .r20(r398_in), .r21(r399_in), .r22(r400_in), .r23(r401_in), .r24(r402_in), .r25(r403_in), .r26(r404_in), .r27(r405_in), .r28(r406_in), .r29(r407_in), .r30(r408_in), .r31(r409_in), .r32(r410_in), .r33(r411_in), .r34(r412_in), .r35(r413_in), .r36(r414_in), .r37(r415_in), .r38(r416_in), .r39(r417_in), .r40(r418_in), .r41(r419_in), .r42(r420_in), .r43(r421_in), .r44(r422_in), .r45(r423_in), .r46(r424_in), .r47(r425_in), .r48(r426_in), .r49(r427_in), .r50(r428_in), .r51(r429_in), .r52(r430_in), .r53(r431_in), .r54(r432_in), .r55(r433_in), .r56(r434_in), .r57(r435_in), .r58(r436_in), .r59(r437_in), .r60(r438_in), .r61(r439_in), .r62(r440_in),
        .valid_out(sb_v[ 6]), .y0_out(sb_y0[ 6]), .y1_out(sb_y1[ 6]), .y2_out(sb_y2[ 6]));
    masked_sbox_second_order u_sbox_7 (
        .clk(clk), .rst_n(rst_n), .valid_in(valid_in),
        .x0_in(x0_in[ 56 +: 8]), .x1_in(x1_in[ 56 +: 8]), .x2_in(x2_in[ 56 +: 8]),
        .r00(r441_in), .r01(r442_in), .r02(r443_in), .r03(r444_in), .r04(r445_in), .r05(r446_in), .r06(r447_in), .r07(r448_in), .r08(r449_in), .r09(r450_in), .r10(r451_in), .r11(r452_in), .r12(r453_in), .r13(r454_in), .r14(r455_in), .r15(r456_in), .r16(r457_in), .r17(r458_in), .r18(r459_in), .r19(r460_in), .r20(r461_in), .r21(r462_in), .r22(r463_in), .r23(r464_in), .r24(r465_in), .r25(r466_in), .r26(r467_in), .r27(r468_in), .r28(r469_in), .r29(r470_in), .r30(r471_in), .r31(r472_in), .r32(r473_in), .r33(r474_in), .r34(r475_in), .r35(r476_in), .r36(r477_in), .r37(r478_in), .r38(r479_in), .r39(r480_in), .r40(r481_in), .r41(r482_in), .r42(r483_in), .r43(r484_in), .r44(r485_in), .r45(r486_in), .r46(r487_in), .r47(r488_in), .r48(r489_in), .r49(r490_in), .r50(r491_in), .r51(r492_in), .r52(r493_in), .r53(r494_in), .r54(r495_in), .r55(r496_in), .r56(r497_in), .r57(r498_in), .r58(r499_in), .r59(r500_in), .r60(r501_in), .r61(r502_in), .r62(r503_in),
        .valid_out(sb_v[ 7]), .y0_out(sb_y0[ 7]), .y1_out(sb_y1[ 7]), .y2_out(sb_y2[ 7]));
    masked_sbox_second_order u_sbox_8 (
        .clk(clk), .rst_n(rst_n), .valid_in(valid_in),
        .x0_in(x0_in[ 64 +: 8]), .x1_in(x1_in[ 64 +: 8]), .x2_in(x2_in[ 64 +: 8]),
        .r00(r504_in), .r01(r505_in), .r02(r506_in), .r03(r507_in), .r04(r508_in), .r05(r509_in), .r06(r510_in), .r07(r511_in), .r08(r512_in), .r09(r513_in), .r10(r514_in), .r11(r515_in), .r12(r516_in), .r13(r517_in), .r14(r518_in), .r15(r519_in), .r16(r520_in), .r17(r521_in), .r18(r522_in), .r19(r523_in), .r20(r524_in), .r21(r525_in), .r22(r526_in), .r23(r527_in), .r24(r528_in), .r25(r529_in), .r26(r530_in), .r27(r531_in), .r28(r532_in), .r29(r533_in), .r30(r534_in), .r31(r535_in), .r32(r536_in), .r33(r537_in), .r34(r538_in), .r35(r539_in), .r36(r540_in), .r37(r541_in), .r38(r542_in), .r39(r543_in), .r40(r544_in), .r41(r545_in), .r42(r546_in), .r43(r547_in), .r44(r548_in), .r45(r549_in), .r46(r550_in), .r47(r551_in), .r48(r552_in), .r49(r553_in), .r50(r554_in), .r51(r555_in), .r52(r556_in), .r53(r557_in), .r54(r558_in), .r55(r559_in), .r56(r560_in), .r57(r561_in), .r58(r562_in), .r59(r563_in), .r60(r564_in), .r61(r565_in), .r62(r566_in),
        .valid_out(sb_v[ 8]), .y0_out(sb_y0[ 8]), .y1_out(sb_y1[ 8]), .y2_out(sb_y2[ 8]));
    masked_sbox_second_order u_sbox_9 (
        .clk(clk), .rst_n(rst_n), .valid_in(valid_in),
        .x0_in(x0_in[ 72 +: 8]), .x1_in(x1_in[ 72 +: 8]), .x2_in(x2_in[ 72 +: 8]),
        .r00(r567_in), .r01(r568_in), .r02(r569_in), .r03(r570_in), .r04(r571_in), .r05(r572_in), .r06(r573_in), .r07(r574_in), .r08(r575_in), .r09(r576_in), .r10(r577_in), .r11(r578_in), .r12(r579_in), .r13(r580_in), .r14(r581_in), .r15(r582_in), .r16(r583_in), .r17(r584_in), .r18(r585_in), .r19(r586_in), .r20(r587_in), .r21(r588_in), .r22(r589_in), .r23(r590_in), .r24(r591_in), .r25(r592_in), .r26(r593_in), .r27(r594_in), .r28(r595_in), .r29(r596_in), .r30(r597_in), .r31(r598_in), .r32(r599_in), .r33(r600_in), .r34(r601_in), .r35(r602_in), .r36(r603_in), .r37(r604_in), .r38(r605_in), .r39(r606_in), .r40(r607_in), .r41(r608_in), .r42(r609_in), .r43(r610_in), .r44(r611_in), .r45(r612_in), .r46(r613_in), .r47(r614_in), .r48(r615_in), .r49(r616_in), .r50(r617_in), .r51(r618_in), .r52(r619_in), .r53(r620_in), .r54(r621_in), .r55(r622_in), .r56(r623_in), .r57(r624_in), .r58(r625_in), .r59(r626_in), .r60(r627_in), .r61(r628_in), .r62(r629_in),
        .valid_out(sb_v[ 9]), .y0_out(sb_y0[ 9]), .y1_out(sb_y1[ 9]), .y2_out(sb_y2[ 9]));
    masked_sbox_second_order u_sbox_10 (
        .clk(clk), .rst_n(rst_n), .valid_in(valid_in),
        .x0_in(x0_in[ 80 +: 8]), .x1_in(x1_in[ 80 +: 8]), .x2_in(x2_in[ 80 +: 8]),
        .r00(r630_in), .r01(r631_in), .r02(r632_in), .r03(r633_in), .r04(r634_in), .r05(r635_in), .r06(r636_in), .r07(r637_in), .r08(r638_in), .r09(r639_in), .r10(r640_in), .r11(r641_in), .r12(r642_in), .r13(r643_in), .r14(r644_in), .r15(r645_in), .r16(r646_in), .r17(r647_in), .r18(r648_in), .r19(r649_in), .r20(r650_in), .r21(r651_in), .r22(r652_in), .r23(r653_in), .r24(r654_in), .r25(r655_in), .r26(r656_in), .r27(r657_in), .r28(r658_in), .r29(r659_in), .r30(r660_in), .r31(r661_in), .r32(r662_in), .r33(r663_in), .r34(r664_in), .r35(r665_in), .r36(r666_in), .r37(r667_in), .r38(r668_in), .r39(r669_in), .r40(r670_in), .r41(r671_in), .r42(r672_in), .r43(r673_in), .r44(r674_in), .r45(r675_in), .r46(r676_in), .r47(r677_in), .r48(r678_in), .r49(r679_in), .r50(r680_in), .r51(r681_in), .r52(r682_in), .r53(r683_in), .r54(r684_in), .r55(r685_in), .r56(r686_in), .r57(r687_in), .r58(r688_in), .r59(r689_in), .r60(r690_in), .r61(r691_in), .r62(r692_in),
        .valid_out(sb_v[10]), .y0_out(sb_y0[10]), .y1_out(sb_y1[10]), .y2_out(sb_y2[10]));
    masked_sbox_second_order u_sbox_11 (
        .clk(clk), .rst_n(rst_n), .valid_in(valid_in),
        .x0_in(x0_in[ 88 +: 8]), .x1_in(x1_in[ 88 +: 8]), .x2_in(x2_in[ 88 +: 8]),
        .r00(r693_in), .r01(r694_in), .r02(r695_in), .r03(r696_in), .r04(r697_in), .r05(r698_in), .r06(r699_in), .r07(r700_in), .r08(r701_in), .r09(r702_in), .r10(r703_in), .r11(r704_in), .r12(r705_in), .r13(r706_in), .r14(r707_in), .r15(r708_in), .r16(r709_in), .r17(r710_in), .r18(r711_in), .r19(r712_in), .r20(r713_in), .r21(r714_in), .r22(r715_in), .r23(r716_in), .r24(r717_in), .r25(r718_in), .r26(r719_in), .r27(r720_in), .r28(r721_in), .r29(r722_in), .r30(r723_in), .r31(r724_in), .r32(r725_in), .r33(r726_in), .r34(r727_in), .r35(r728_in), .r36(r729_in), .r37(r730_in), .r38(r731_in), .r39(r732_in), .r40(r733_in), .r41(r734_in), .r42(r735_in), .r43(r736_in), .r44(r737_in), .r45(r738_in), .r46(r739_in), .r47(r740_in), .r48(r741_in), .r49(r742_in), .r50(r743_in), .r51(r744_in), .r52(r745_in), .r53(r746_in), .r54(r747_in), .r55(r748_in), .r56(r749_in), .r57(r750_in), .r58(r751_in), .r59(r752_in), .r60(r753_in), .r61(r754_in), .r62(r755_in),
        .valid_out(sb_v[11]), .y0_out(sb_y0[11]), .y1_out(sb_y1[11]), .y2_out(sb_y2[11]));
    masked_sbox_second_order u_sbox_12 (
        .clk(clk), .rst_n(rst_n), .valid_in(valid_in),
        .x0_in(x0_in[ 96 +: 8]), .x1_in(x1_in[ 96 +: 8]), .x2_in(x2_in[ 96 +: 8]),
        .r00(r756_in), .r01(r757_in), .r02(r758_in), .r03(r759_in), .r04(r760_in), .r05(r761_in), .r06(r762_in), .r07(r763_in), .r08(r764_in), .r09(r765_in), .r10(r766_in), .r11(r767_in), .r12(r768_in), .r13(r769_in), .r14(r770_in), .r15(r771_in), .r16(r772_in), .r17(r773_in), .r18(r774_in), .r19(r775_in), .r20(r776_in), .r21(r777_in), .r22(r778_in), .r23(r779_in), .r24(r780_in), .r25(r781_in), .r26(r782_in), .r27(r783_in), .r28(r784_in), .r29(r785_in), .r30(r786_in), .r31(r787_in), .r32(r788_in), .r33(r789_in), .r34(r790_in), .r35(r791_in), .r36(r792_in), .r37(r793_in), .r38(r794_in), .r39(r795_in), .r40(r796_in), .r41(r797_in), .r42(r798_in), .r43(r799_in), .r44(r800_in), .r45(r801_in), .r46(r802_in), .r47(r803_in), .r48(r804_in), .r49(r805_in), .r50(r806_in), .r51(r807_in), .r52(r808_in), .r53(r809_in), .r54(r810_in), .r55(r811_in), .r56(r812_in), .r57(r813_in), .r58(r814_in), .r59(r815_in), .r60(r816_in), .r61(r817_in), .r62(r818_in),
        .valid_out(sb_v[12]), .y0_out(sb_y0[12]), .y1_out(sb_y1[12]), .y2_out(sb_y2[12]));
    masked_sbox_second_order u_sbox_13 (
        .clk(clk), .rst_n(rst_n), .valid_in(valid_in),
        .x0_in(x0_in[104 +: 8]), .x1_in(x1_in[104 +: 8]), .x2_in(x2_in[104 +: 8]),
        .r00(r819_in), .r01(r820_in), .r02(r821_in), .r03(r822_in), .r04(r823_in), .r05(r824_in), .r06(r825_in), .r07(r826_in), .r08(r827_in), .r09(r828_in), .r10(r829_in), .r11(r830_in), .r12(r831_in), .r13(r832_in), .r14(r833_in), .r15(r834_in), .r16(r835_in), .r17(r836_in), .r18(r837_in), .r19(r838_in), .r20(r839_in), .r21(r840_in), .r22(r841_in), .r23(r842_in), .r24(r843_in), .r25(r844_in), .r26(r845_in), .r27(r846_in), .r28(r847_in), .r29(r848_in), .r30(r849_in), .r31(r850_in), .r32(r851_in), .r33(r852_in), .r34(r853_in), .r35(r854_in), .r36(r855_in), .r37(r856_in), .r38(r857_in), .r39(r858_in), .r40(r859_in), .r41(r860_in), .r42(r861_in), .r43(r862_in), .r44(r863_in), .r45(r864_in), .r46(r865_in), .r47(r866_in), .r48(r867_in), .r49(r868_in), .r50(r869_in), .r51(r870_in), .r52(r871_in), .r53(r872_in), .r54(r873_in), .r55(r874_in), .r56(r875_in), .r57(r876_in), .r58(r877_in), .r59(r878_in), .r60(r879_in), .r61(r880_in), .r62(r881_in),
        .valid_out(sb_v[13]), .y0_out(sb_y0[13]), .y1_out(sb_y1[13]), .y2_out(sb_y2[13]));
    masked_sbox_second_order u_sbox_14 (
        .clk(clk), .rst_n(rst_n), .valid_in(valid_in),
        .x0_in(x0_in[112 +: 8]), .x1_in(x1_in[112 +: 8]), .x2_in(x2_in[112 +: 8]),
        .r00(r882_in), .r01(r883_in), .r02(r884_in), .r03(r885_in), .r04(r886_in), .r05(r887_in), .r06(r888_in), .r07(r889_in), .r08(r890_in), .r09(r891_in), .r10(r892_in), .r11(r893_in), .r12(r894_in), .r13(r895_in), .r14(r896_in), .r15(r897_in), .r16(r898_in), .r17(r899_in), .r18(r900_in), .r19(r901_in), .r20(r902_in), .r21(r903_in), .r22(r904_in), .r23(r905_in), .r24(r906_in), .r25(r907_in), .r26(r908_in), .r27(r909_in), .r28(r910_in), .r29(r911_in), .r30(r912_in), .r31(r913_in), .r32(r914_in), .r33(r915_in), .r34(r916_in), .r35(r917_in), .r36(r918_in), .r37(r919_in), .r38(r920_in), .r39(r921_in), .r40(r922_in), .r41(r923_in), .r42(r924_in), .r43(r925_in), .r44(r926_in), .r45(r927_in), .r46(r928_in), .r47(r929_in), .r48(r930_in), .r49(r931_in), .r50(r932_in), .r51(r933_in), .r52(r934_in), .r53(r935_in), .r54(r936_in), .r55(r937_in), .r56(r938_in), .r57(r939_in), .r58(r940_in), .r59(r941_in), .r60(r942_in), .r61(r943_in), .r62(r944_in),
        .valid_out(sb_v[14]), .y0_out(sb_y0[14]), .y1_out(sb_y1[14]), .y2_out(sb_y2[14]));
    masked_sbox_second_order u_sbox_15 (
        .clk(clk), .rst_n(rst_n), .valid_in(valid_in),
        .x0_in(x0_in[120 +: 8]), .x1_in(x1_in[120 +: 8]), .x2_in(x2_in[120 +: 8]),
        .r00(r945_in), .r01(r946_in), .r02(r947_in), .r03(r948_in), .r04(r949_in), .r05(r950_in), .r06(r951_in), .r07(r952_in), .r08(r953_in), .r09(r954_in), .r10(r955_in), .r11(r956_in), .r12(r957_in), .r13(r958_in), .r14(r959_in), .r15(r960_in), .r16(r961_in), .r17(r962_in), .r18(r963_in), .r19(r964_in), .r20(r965_in), .r21(r966_in), .r22(r967_in), .r23(r968_in), .r24(r969_in), .r25(r970_in), .r26(r971_in), .r27(r972_in), .r28(r973_in), .r29(r974_in), .r30(r975_in), .r31(r976_in), .r32(r977_in), .r33(r978_in), .r34(r979_in), .r35(r980_in), .r36(r981_in), .r37(r982_in), .r38(r983_in), .r39(r984_in), .r40(r985_in), .r41(r986_in), .r42(r987_in), .r43(r988_in), .r44(r989_in), .r45(r990_in), .r46(r991_in), .r47(r992_in), .r48(r993_in), .r49(r994_in), .r50(r995_in), .r51(r996_in), .r52(r997_in), .r53(r998_in), .r54(r999_in), .r55(r1000_in), .r56(r1001_in), .r57(r1002_in), .r58(r1003_in), .r59(r1004_in), .r60(r1005_in), .r61(r1006_in), .r62(r1007_in),
        .valid_out(sb_v[15]), .y0_out(sb_y0[15]), .y1_out(sb_y1[15]), .y2_out(sb_y2[15]));

    wire sb_v_all = sb_v[ 0] & sb_v[ 1] & sb_v[ 2] & sb_v[ 3] & sb_v[ 4] & sb_v[ 5] & sb_v[ 6] & sb_v[ 7] & sb_v[ 8] & sb_v[ 9] & sb_v[10] & sb_v[11] & sb_v[12] & sb_v[13] & sb_v[14] & sb_v[15];

    // ---- Share y0 ----
    wire [127:0] sr_state_y0;
    assign sr_state_y0[ 0 +: 8] = sb_state_y0[ 0 +: 8];
    assign sr_state_y0[ 1 +: 8] = sb_state_y0[13 +: 8];
    assign sr_state_y0[ 2 +: 8] = sb_state_y0[10 +: 8];
    assign sr_state_y0[ 3 +: 8] = sb_state_y0[ 7 +: 8];
    assign sr_state_y0[ 4 +: 8] = sb_state_y0[ 4 +: 8];
    assign sr_state_y0[ 5 +: 8] = sb_state_y0[ 1 +: 8];
    assign sr_state_y0[ 6 +: 8] = sb_state_y0[14 +: 8];
    assign sr_state_y0[ 7 +: 8] = sb_state_y0[11 +: 8];
    assign sr_state_y0[ 8 +: 8] = sb_state_y0[ 8 +: 8];
    assign sr_state_y0[ 9 +: 8] = sb_state_y0[ 5 +: 8];
    assign sr_state_y0[10 +: 8] = sb_state_y0[ 2 +: 8];
    assign sr_state_y0[11 +: 8] = sb_state_y0[15 +: 8];
    assign sr_state_y0[12 +: 8] = sb_state_y0[12 +: 8];
    assign sr_state_y0[13 +: 8] = sb_state_y0[ 9 +: 8];
    assign sr_state_y0[14 +: 8] = sb_state_y0[ 6 +: 8];
    assign sr_state_y0[15 +: 8] = sb_state_y0[ 3 +: 8];
    wire [127:0] mc_state_y0;
    assign mc_state_y0[ 0 +: 8] = xtime_f(sr_state_y0[ 0 +: 8]) ^ (xtime_f(sr_state_y0[ 1 +: 8]) ^ sr_state_y0[ 1 +: 8]) ^ sr_state_y0[ 2 +: 8] ^ sr_state_y0[ 3 +: 8];
    assign mc_state_y0[ 1 +: 8] = sr_state_y0[ 0 +: 8] ^ xtime_f(sr_state_y0[ 1 +: 8]) ^ (xtime_f(sr_state_y0[ 2 +: 8]) ^ sr_state_y0[ 2 +: 8]) ^ sr_state_y0[ 3 +: 8];
    assign mc_state_y0[ 2 +: 8] = sr_state_y0[ 0 +: 8] ^ sr_state_y0[ 1 +: 8] ^ xtime_f(sr_state_y0[ 2 +: 8]) ^ (xtime_f(sr_state_y0[ 3 +: 8]) ^ sr_state_y0[ 3 +: 8]);
    assign mc_state_y0[ 3 +: 8] = (xtime_f(sr_state_y0[ 0 +: 8]) ^ sr_state_y0[ 0 +: 8]) ^ sr_state_y0[ 1 +: 8] ^ sr_state_y0[ 2 +: 8] ^ xtime_f(sr_state_y0[ 3 +: 8]);
    assign mc_state_y0[ 4 +: 8] = xtime_f(sr_state_y0[ 4 +: 8]) ^ (xtime_f(sr_state_y0[ 5 +: 8]) ^ sr_state_y0[ 5 +: 8]) ^ sr_state_y0[ 6 +: 8] ^ sr_state_y0[ 7 +: 8];
    assign mc_state_y0[ 5 +: 8] = sr_state_y0[ 4 +: 8] ^ xtime_f(sr_state_y0[ 5 +: 8]) ^ (xtime_f(sr_state_y0[ 6 +: 8]) ^ sr_state_y0[ 6 +: 8]) ^ sr_state_y0[ 7 +: 8];
    assign mc_state_y0[ 6 +: 8] = sr_state_y0[ 4 +: 8] ^ sr_state_y0[ 5 +: 8] ^ xtime_f(sr_state_y0[ 6 +: 8]) ^ (xtime_f(sr_state_y0[ 7 +: 8]) ^ sr_state_y0[ 7 +: 8]);
    assign mc_state_y0[ 7 +: 8] = (xtime_f(sr_state_y0[ 4 +: 8]) ^ sr_state_y0[ 4 +: 8]) ^ sr_state_y0[ 5 +: 8] ^ sr_state_y0[ 6 +: 8] ^ xtime_f(sr_state_y0[ 7 +: 8]);
    assign mc_state_y0[ 8 +: 8] = xtime_f(sr_state_y0[ 8 +: 8]) ^ (xtime_f(sr_state_y0[ 9 +: 8]) ^ sr_state_y0[ 9 +: 8]) ^ sr_state_y0[10 +: 8] ^ sr_state_y0[11 +: 8];
    assign mc_state_y0[ 9 +: 8] = sr_state_y0[ 8 +: 8] ^ xtime_f(sr_state_y0[ 9 +: 8]) ^ (xtime_f(sr_state_y0[10 +: 8]) ^ sr_state_y0[10 +: 8]) ^ sr_state_y0[11 +: 8];
    assign mc_state_y0[10 +: 8] = sr_state_y0[ 8 +: 8] ^ sr_state_y0[ 9 +: 8] ^ xtime_f(sr_state_y0[10 +: 8]) ^ (xtime_f(sr_state_y0[11 +: 8]) ^ sr_state_y0[11 +: 8]);
    assign mc_state_y0[11 +: 8] = (xtime_f(sr_state_y0[ 8 +: 8]) ^ sr_state_y0[ 8 +: 8]) ^ sr_state_y0[ 9 +: 8] ^ sr_state_y0[10 +: 8] ^ xtime_f(sr_state_y0[11 +: 8]);
    assign mc_state_y0[12 +: 8] = xtime_f(sr_state_y0[12 +: 8]) ^ (xtime_f(sr_state_y0[13 +: 8]) ^ sr_state_y0[13 +: 8]) ^ sr_state_y0[14 +: 8] ^ sr_state_y0[15 +: 8];
    assign mc_state_y0[13 +: 8] = sr_state_y0[12 +: 8] ^ xtime_f(sr_state_y0[13 +: 8]) ^ (xtime_f(sr_state_y0[14 +: 8]) ^ sr_state_y0[14 +: 8]) ^ sr_state_y0[15 +: 8];
    assign mc_state_y0[14 +: 8] = sr_state_y0[12 +: 8] ^ sr_state_y0[13 +: 8] ^ xtime_f(sr_state_y0[14 +: 8]) ^ (xtime_f(sr_state_y0[15 +: 8]) ^ sr_state_y0[15 +: 8]);
    assign mc_state_y0[15 +: 8] = (xtime_f(sr_state_y0[12 +: 8]) ^ sr_state_y0[12 +: 8]) ^ sr_state_y0[13 +: 8] ^ sr_state_y0[14 +: 8] ^ xtime_f(sr_state_y0[15 +: 8]);

    // ---- Share y1 ----
    wire [127:0] sr_state_y1;
    assign sr_state_y1[ 0 +: 8] = sb_state_y1[ 0 +: 8];
    assign sr_state_y1[ 1 +: 8] = sb_state_y1[13 +: 8];
    assign sr_state_y1[ 2 +: 8] = sb_state_y1[10 +: 8];
    assign sr_state_y1[ 3 +: 8] = sb_state_y1[ 7 +: 8];
    assign sr_state_y1[ 4 +: 8] = sb_state_y1[ 4 +: 8];
    assign sr_state_y1[ 5 +: 8] = sb_state_y1[ 1 +: 8];
    assign sr_state_y1[ 6 +: 8] = sb_state_y1[14 +: 8];
    assign sr_state_y1[ 7 +: 8] = sb_state_y1[11 +: 8];
    assign sr_state_y1[ 8 +: 8] = sb_state_y1[ 8 +: 8];
    assign sr_state_y1[ 9 +: 8] = sb_state_y1[ 5 +: 8];
    assign sr_state_y1[10 +: 8] = sb_state_y1[ 2 +: 8];
    assign sr_state_y1[11 +: 8] = sb_state_y1[15 +: 8];
    assign sr_state_y1[12 +: 8] = sb_state_y1[12 +: 8];
    assign sr_state_y1[13 +: 8] = sb_state_y1[ 9 +: 8];
    assign sr_state_y1[14 +: 8] = sb_state_y1[ 6 +: 8];
    assign sr_state_y1[15 +: 8] = sb_state_y1[ 3 +: 8];
    wire [127:0] mc_state_y1;
    assign mc_state_y1[ 0 +: 8] = xtime_f(sr_state_y1[ 0 +: 8]) ^ (xtime_f(sr_state_y1[ 1 +: 8]) ^ sr_state_y1[ 1 +: 8]) ^ sr_state_y1[ 2 +: 8] ^ sr_state_y1[ 3 +: 8];
    assign mc_state_y1[ 1 +: 8] = sr_state_y1[ 0 +: 8] ^ xtime_f(sr_state_y1[ 1 +: 8]) ^ (xtime_f(sr_state_y1[ 2 +: 8]) ^ sr_state_y1[ 2 +: 8]) ^ sr_state_y1[ 3 +: 8];
    assign mc_state_y1[ 2 +: 8] = sr_state_y1[ 0 +: 8] ^ sr_state_y1[ 1 +: 8] ^ xtime_f(sr_state_y1[ 2 +: 8]) ^ (xtime_f(sr_state_y1[ 3 +: 8]) ^ sr_state_y1[ 3 +: 8]);
    assign mc_state_y1[ 3 +: 8] = (xtime_f(sr_state_y1[ 0 +: 8]) ^ sr_state_y1[ 0 +: 8]) ^ sr_state_y1[ 1 +: 8] ^ sr_state_y1[ 2 +: 8] ^ xtime_f(sr_state_y1[ 3 +: 8]);
    assign mc_state_y1[ 4 +: 8] = xtime_f(sr_state_y1[ 4 +: 8]) ^ (xtime_f(sr_state_y1[ 5 +: 8]) ^ sr_state_y1[ 5 +: 8]) ^ sr_state_y1[ 6 +: 8] ^ sr_state_y1[ 7 +: 8];
    assign mc_state_y1[ 5 +: 8] = sr_state_y1[ 4 +: 8] ^ xtime_f(sr_state_y1[ 5 +: 8]) ^ (xtime_f(sr_state_y1[ 6 +: 8]) ^ sr_state_y1[ 6 +: 8]) ^ sr_state_y1[ 7 +: 8];
    assign mc_state_y1[ 6 +: 8] = sr_state_y1[ 4 +: 8] ^ sr_state_y1[ 5 +: 8] ^ xtime_f(sr_state_y1[ 6 +: 8]) ^ (xtime_f(sr_state_y1[ 7 +: 8]) ^ sr_state_y1[ 7 +: 8]);
    assign mc_state_y1[ 7 +: 8] = (xtime_f(sr_state_y1[ 4 +: 8]) ^ sr_state_y1[ 4 +: 8]) ^ sr_state_y1[ 5 +: 8] ^ sr_state_y1[ 6 +: 8] ^ xtime_f(sr_state_y1[ 7 +: 8]);
    assign mc_state_y1[ 8 +: 8] = xtime_f(sr_state_y1[ 8 +: 8]) ^ (xtime_f(sr_state_y1[ 9 +: 8]) ^ sr_state_y1[ 9 +: 8]) ^ sr_state_y1[10 +: 8] ^ sr_state_y1[11 +: 8];
    assign mc_state_y1[ 9 +: 8] = sr_state_y1[ 8 +: 8] ^ xtime_f(sr_state_y1[ 9 +: 8]) ^ (xtime_f(sr_state_y1[10 +: 8]) ^ sr_state_y1[10 +: 8]) ^ sr_state_y1[11 +: 8];
    assign mc_state_y1[10 +: 8] = sr_state_y1[ 8 +: 8] ^ sr_state_y1[ 9 +: 8] ^ xtime_f(sr_state_y1[10 +: 8]) ^ (xtime_f(sr_state_y1[11 +: 8]) ^ sr_state_y1[11 +: 8]);
    assign mc_state_y1[11 +: 8] = (xtime_f(sr_state_y1[ 8 +: 8]) ^ sr_state_y1[ 8 +: 8]) ^ sr_state_y1[ 9 +: 8] ^ sr_state_y1[10 +: 8] ^ xtime_f(sr_state_y1[11 +: 8]);
    assign mc_state_y1[12 +: 8] = xtime_f(sr_state_y1[12 +: 8]) ^ (xtime_f(sr_state_y1[13 +: 8]) ^ sr_state_y1[13 +: 8]) ^ sr_state_y1[14 +: 8] ^ sr_state_y1[15 +: 8];
    assign mc_state_y1[13 +: 8] = sr_state_y1[12 +: 8] ^ xtime_f(sr_state_y1[13 +: 8]) ^ (xtime_f(sr_state_y1[14 +: 8]) ^ sr_state_y1[14 +: 8]) ^ sr_state_y1[15 +: 8];
    assign mc_state_y1[14 +: 8] = sr_state_y1[12 +: 8] ^ sr_state_y1[13 +: 8] ^ xtime_f(sr_state_y1[14 +: 8]) ^ (xtime_f(sr_state_y1[15 +: 8]) ^ sr_state_y1[15 +: 8]);
    assign mc_state_y1[15 +: 8] = (xtime_f(sr_state_y1[12 +: 8]) ^ sr_state_y1[12 +: 8]) ^ sr_state_y1[13 +: 8] ^ sr_state_y1[14 +: 8] ^ xtime_f(sr_state_y1[15 +: 8]);

    // ---- Share y2 ----
    wire [127:0] sr_state_y2;
    assign sr_state_y2[ 0 +: 8] = sb_state_y2[ 0 +: 8];
    assign sr_state_y2[ 1 +: 8] = sb_state_y2[13 +: 8];
    assign sr_state_y2[ 2 +: 8] = sb_state_y2[10 +: 8];
    assign sr_state_y2[ 3 +: 8] = sb_state_y2[ 7 +: 8];
    assign sr_state_y2[ 4 +: 8] = sb_state_y2[ 4 +: 8];
    assign sr_state_y2[ 5 +: 8] = sb_state_y2[ 1 +: 8];
    assign sr_state_y2[ 6 +: 8] = sb_state_y2[14 +: 8];
    assign sr_state_y2[ 7 +: 8] = sb_state_y2[11 +: 8];
    assign sr_state_y2[ 8 +: 8] = sb_state_y2[ 8 +: 8];
    assign sr_state_y2[ 9 +: 8] = sb_state_y2[ 5 +: 8];
    assign sr_state_y2[10 +: 8] = sb_state_y2[ 2 +: 8];
    assign sr_state_y2[11 +: 8] = sb_state_y2[15 +: 8];
    assign sr_state_y2[12 +: 8] = sb_state_y2[12 +: 8];
    assign sr_state_y2[13 +: 8] = sb_state_y2[ 9 +: 8];
    assign sr_state_y2[14 +: 8] = sb_state_y2[ 6 +: 8];
    assign sr_state_y2[15 +: 8] = sb_state_y2[ 3 +: 8];
    wire [127:0] mc_state_y2;
    assign mc_state_y2[ 0 +: 8] = xtime_f(sr_state_y2[ 0 +: 8]) ^ (xtime_f(sr_state_y2[ 1 +: 8]) ^ sr_state_y2[ 1 +: 8]) ^ sr_state_y2[ 2 +: 8] ^ sr_state_y2[ 3 +: 8];
    assign mc_state_y2[ 1 +: 8] = sr_state_y2[ 0 +: 8] ^ xtime_f(sr_state_y2[ 1 +: 8]) ^ (xtime_f(sr_state_y2[ 2 +: 8]) ^ sr_state_y2[ 2 +: 8]) ^ sr_state_y2[ 3 +: 8];
    assign mc_state_y2[ 2 +: 8] = sr_state_y2[ 0 +: 8] ^ sr_state_y2[ 1 +: 8] ^ xtime_f(sr_state_y2[ 2 +: 8]) ^ (xtime_f(sr_state_y2[ 3 +: 8]) ^ sr_state_y2[ 3 +: 8]);
    assign mc_state_y2[ 3 +: 8] = (xtime_f(sr_state_y2[ 0 +: 8]) ^ sr_state_y2[ 0 +: 8]) ^ sr_state_y2[ 1 +: 8] ^ sr_state_y2[ 2 +: 8] ^ xtime_f(sr_state_y2[ 3 +: 8]);
    assign mc_state_y2[ 4 +: 8] = xtime_f(sr_state_y2[ 4 +: 8]) ^ (xtime_f(sr_state_y2[ 5 +: 8]) ^ sr_state_y2[ 5 +: 8]) ^ sr_state_y2[ 6 +: 8] ^ sr_state_y2[ 7 +: 8];
    assign mc_state_y2[ 5 +: 8] = sr_state_y2[ 4 +: 8] ^ xtime_f(sr_state_y2[ 5 +: 8]) ^ (xtime_f(sr_state_y2[ 6 +: 8]) ^ sr_state_y2[ 6 +: 8]) ^ sr_state_y2[ 7 +: 8];
    assign mc_state_y2[ 6 +: 8] = sr_state_y2[ 4 +: 8] ^ sr_state_y2[ 5 +: 8] ^ xtime_f(sr_state_y2[ 6 +: 8]) ^ (xtime_f(sr_state_y2[ 7 +: 8]) ^ sr_state_y2[ 7 +: 8]);
    assign mc_state_y2[ 7 +: 8] = (xtime_f(sr_state_y2[ 4 +: 8]) ^ sr_state_y2[ 4 +: 8]) ^ sr_state_y2[ 5 +: 8] ^ sr_state_y2[ 6 +: 8] ^ xtime_f(sr_state_y2[ 7 +: 8]);
    assign mc_state_y2[ 8 +: 8] = xtime_f(sr_state_y2[ 8 +: 8]) ^ (xtime_f(sr_state_y2[ 9 +: 8]) ^ sr_state_y2[ 9 +: 8]) ^ sr_state_y2[10 +: 8] ^ sr_state_y2[11 +: 8];
    assign mc_state_y2[ 9 +: 8] = sr_state_y2[ 8 +: 8] ^ xtime_f(sr_state_y2[ 9 +: 8]) ^ (xtime_f(sr_state_y2[10 +: 8]) ^ sr_state_y2[10 +: 8]) ^ sr_state_y2[11 +: 8];
    assign mc_state_y2[10 +: 8] = sr_state_y2[ 8 +: 8] ^ sr_state_y2[ 9 +: 8] ^ xtime_f(sr_state_y2[10 +: 8]) ^ (xtime_f(sr_state_y2[11 +: 8]) ^ sr_state_y2[11 +: 8]);
    assign mc_state_y2[11 +: 8] = (xtime_f(sr_state_y2[ 8 +: 8]) ^ sr_state_y2[ 8 +: 8]) ^ sr_state_y2[ 9 +: 8] ^ sr_state_y2[10 +: 8] ^ xtime_f(sr_state_y2[11 +: 8]);
    assign mc_state_y2[12 +: 8] = xtime_f(sr_state_y2[12 +: 8]) ^ (xtime_f(sr_state_y2[13 +: 8]) ^ sr_state_y2[13 +: 8]) ^ sr_state_y2[14 +: 8] ^ sr_state_y2[15 +: 8];
    assign mc_state_y2[13 +: 8] = sr_state_y2[12 +: 8] ^ xtime_f(sr_state_y2[13 +: 8]) ^ (xtime_f(sr_state_y2[14 +: 8]) ^ sr_state_y2[14 +: 8]) ^ sr_state_y2[15 +: 8];
    assign mc_state_y2[14 +: 8] = sr_state_y2[12 +: 8] ^ sr_state_y2[13 +: 8] ^ xtime_f(sr_state_y2[14 +: 8]) ^ (xtime_f(sr_state_y2[15 +: 8]) ^ sr_state_y2[15 +: 8]);
    assign mc_state_y2[15 +: 8] = (xtime_f(sr_state_y2[12 +: 8]) ^ sr_state_y2[12 +: 8]) ^ sr_state_y2[13 +: 8] ^ sr_state_y2[14 +: 8] ^ xtime_f(sr_state_y2[15 +: 8]);
    // ----------------------------------------------------------------
    // STAGE 4: AddRoundKey (clocked register, share-wise XOR)
    // ----------------------------------------------------------------
    reg [127:0] ark_state_y0;
    reg [127:0] ark_state_y1;
    reg [127:0] ark_state_y2;

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            ark_state_y0 <= 128'h0;
            ark_state_y1 <= 128'h0;
            ark_state_y2 <= 128'h0;
        end else begin
            ark_state_y0 <= mc_state_y0 ^ rk0_in;
            ark_state_y1 <= mc_state_y1 ^ rk1_in;
            ark_state_y2 <= mc_state_y2 ^ rk2_in;
        end
    end

    // ----------------------------------------------------------------
    // STAGE 5: output register
    // ----------------------------------------------------------------
    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            y0_out <= 128'h0;
            y1_out <= 128'h0;
            y2_out <= 128'h0;
        end else begin
            y0_out <= ark_state_y0;
            y1_out <= ark_state_y1;
            y2_out <= ark_state_y2;
        end
    end

    // valid_out: combinational from sb_v_all.  12-cycle data
    // latency = 10 (S-box pipeline) + 1 (ARK) + 1 (output register).
    assign valid_out = sb_v_all;

endmodule
