// =====================================================================
// tb_aes_10rounds.v
// =====================================================================
// Smoke test for the 10-round masked AES-128 skeleton
// (`masked_aes_10rounds_first_order.v`).  Since only round 1 is
// wired in the skeleton, this testbench validates the structural
// instantiation and basic reset/valid behavior; a full 10-round
// functional test would require all 4,480 mask bytes and 120
// cycles of latency per vector.
//
// Test vectors are read from sim/round10_*.txt, generated by
// reference/gen_10round_vectors.py.
//
// Usage:
//   python3 reference/gen_10round_vectors.py
//   iverilog -g2012 -I . -o /tmp/tb_10r.vvp \
//     tb_aes_10rounds.v \
//     masked_aes_10rounds_first_order.v \
//     masked_sbox_first_order.v masked_sbox_pkg.v \
//     masked_aes_round1.v
//   vvp /tmp/tb_10r.vvp
// =====================================================================

`ifndef TB_AES_10ROUNDS_V
`define TB_AES_10ROUNDS_V

`timescale 1ns/1ps

module tb_aes_10rounds;

    integer N_VECTORS = 5;

    reg clk;
    initial begin
        clk = 1'b0;
        forever #5 clk = ~clk;
    end

    reg               rst_n;
    reg               valid_in;
    reg  [127:0]      x0_in, x1_in, rk0_in, rk1_in;
    wire              valid_out;
    wire [127:0]      y0_out, y1_out;

    // DUT — the 10-round skeleton (only round 1 wired)
    masked_aes_10rounds_first_order u_dut (
        .clk(clk), .rst_n(rst_n), .valid_in(valid_in),
        .x0_in(x0_in), .x1_in(x1_in), .rk0_in(rk0_in), .rk1_in(rk1_in),
        .r000_in(8'h0),  .r001_in(8'h0),  .r002_in(8'h0),  .r003_in(8'h0),
        .r004_in(8'h0),  .r005_in(8'h0),  .r006_in(8'h0),  .r007_in(8'h0),
        .r008_in(8'h0),  .r009_in(8'h0),  .r010_in(8'h0),  .r011_in(8'h0),
        .r012_in(8'h0),  .r013_in(8'h0),  .r014_in(8'h0),  .r015_in(8'h0),
        .valid_out(valid_out), .y0_out(y0_out), .y1_out(y1_out)
    );

    reg [127:0] h_pt  [0:99];
    reg [127:0] h_key [0:99];

    initial begin
        if (!$value$plusargs("N=%d", N_VECTORS)) N_VECTORS = 5;
        $readmemh("sim/round10_pt.txt",  h_pt);
        $readmemh("sim/round10_key.txt", h_key);
    end

    integer n;
    initial begin
        #1;
        valid_in = 1'b0;
        x0_in    = 128'h0; x1_in    = 128'h0;
        rk0_in   = 128'h0; rk1_in   = 128'h0;
        rst_n    = 1'b0;
        repeat (4) @(posedge clk);
        rst_n    = 1'b1;
        @(posedge clk);

        // Smoke test: present a few plaintexts and watch the
        // valid_out signal pulse 12 cycles after each input.
        for (n = 0; n < N_VECTORS; n = n + 1) begin : VEC_LOOP
            x0_in  = h_pt[n];
            x1_in  = 128'h0;
            rk0_in = h_key[n];
            rk1_in = 128'h0;
            @(posedge clk);
            valid_in = 1'b1;
            @(posedge clk);
            valid_in = 1'b0;
            repeat (16) @(posedge clk);
            $display("vec %0d: valid_out=%b y0_out=%032h y1_out=%032h",
                     n, valid_out, y0_out, y1_out);
        end
        $display("tb_aes_10rounds: %0d vectors, skeleton only (round 1 wired)",
                 N_VECTORS);
        $finish;
    end

endmodule

`endif
