// =====================================================================
// tb_aes_10rounds.v
// =====================================================================
// Smoke test for the 10-round masked AES-128 skeleton
// (`masked_aes_10rounds_first_order.v`).  Since only round 1 is
// wired in the skeleton, this testbench validates the structural
// instantiation and basic reset/valid behavior; a full 10-round
// functional test would require all 960 mask bytes and 190
// cycles of latency per vector.
//
// Test vectors are read from sim/round10_*.txt, generated by
// reference/gen_10round_vectors.py.
//
// Usage:
//   python3 reference/gen_10round_vectors.py
//   iverilog -g2012 -I . -o /tmp/tb_10r.vvp \
//     tb_aes_10rounds.v \
//     masked_aes_10rounds_first_order.v \
//     masked_sbox_first_order.v masked_sbox_pkg.v \
//     masked_aes_round1.v
//   vvp /tmp/tb_10r.vvp
// =====================================================================

`ifndef TB_AES_10ROUNDS_V
`define TB_AES_10ROUNDS_V

`timescale 1ns/1ps

module tb_aes_10rounds;

    integer N_VECTORS = 5;

    reg clk;
    initial begin
        clk = 1'b0;
        forever #5 clk = ~clk;
    end

    reg               rst_n;
    reg               valid_in;
    reg  [127:0]      x0_in, x1_in, rk0_in, rk1_in;
    wire              valid_out;
    wire [127:0]      y0_out, y1_out;

    // DUT — the 10-round skeleton (only round 1 wired)
    masked_aes_10rounds_first_order u_dut (
        .clk(clk), .rst_n(rst_n), .valid_in(valid_in),
        .x0_in(x0_in), .x1_in(x1_in), .rk0_in(rk0_in), .rk1_in(rk1_in),
        .r000_in(8'h0),  .r001_in(8'h0),  .r002_in(8'h0),  .r003_in(8'h0),
        .r004_in(8'h0),  .r005_in(8'h0),  .r006_in(8'h0),  .r007_in(8'h0),
        .r008_in(8'h0),  .r009_in(8'h0),  .r010_in(8'h0),  .r011_in(8'h0),
        .r012_in(8'h0),  .r013_in(8'h0),  .r014_in(8'h0),  .r015_in(8'h0),
        .r016_in(8'h0),  .r017_in(8'h0),  .r018_in(8'h0),  .r019_in(8'h0),
        .r020_in(8'h0),  .r021_in(8'h0),  .r022_in(8'h0),  .r023_in(8'h0),
        .r024_in(8'h0),  .r025_in(8'h0),  .r026_in(8'h0),  .r027_in(8'h0),
        .r028_in(8'h0),  .r029_in(8'h0),  .r030_in(8'h0),  .r031_in(8'h0),
        .r032_in(8'h0),  .r033_in(8'h0),  .r034_in(8'h0),  .r035_in(8'h0),
        .r036_in(8'h0),  .r037_in(8'h0),  .r038_in(8'h0),  .r039_in(8'h0),
        .r040_in(8'h0),  .r041_in(8'h0),  .r042_in(8'h0),  .r043_in(8'h0),
        .r044_in(8'h0),  .r045_in(8'h0),  .r046_in(8'h0),  .r047_in(8'h0),
        .r048_in(8'h0),  .r049_in(8'h0),  .r050_in(8'h0),  .r051_in(8'h0),
        .r052_in(8'h0),  .r053_in(8'h0),  .r054_in(8'h0),  .r055_in(8'h0),
        .r056_in(8'h0),  .r057_in(8'h0),  .r058_in(8'h0),  .r059_in(8'h0),
        .r060_in(8'h0),  .r061_in(8'h0),  .r062_in(8'h0),  .r063_in(8'h0),
        .r064_in(8'h0),  .r065_in(8'h0),  .r066_in(8'h0),  .r067_in(8'h0),
        .r068_in(8'h0),  .r069_in(8'h0),  .r070_in(8'h0),  .r071_in(8'h0),
        .r072_in(8'h0),  .r073_in(8'h0),  .r074_in(8'h0),  .r075_in(8'h0),
        .r076_in(8'h0),  .r077_in(8'h0),  .r078_in(8'h0),  .r079_in(8'h0),
        .r080_in(8'h0),  .r081_in(8'h0),  .r082_in(8'h0),  .r083_in(8'h0),
        .r084_in(8'h0),  .r085_in(8'h0),  .r086_in(8'h0),  .r087_in(8'h0),
        .r088_in(8'h0),  .r089_in(8'h0),  .r090_in(8'h0),  .r091_in(8'h0),
        .r092_in(8'h0),  .r093_in(8'h0),  .r094_in(8'h0),  .r095_in(8'h0),
        .r096_in(8'h0),  .r097_in(8'h0),  .r098_in(8'h0),  .r099_in(8'h0),
        .r100_in(8'h0),  .r101_in(8'h0),  .r102_in(8'h0),  .r103_in(8'h0),
        .r104_in(8'h0),  .r105_in(8'h0),  .r106_in(8'h0),  .r107_in(8'h0),
        .r108_in(8'h0),  .r109_in(8'h0),  .r110_in(8'h0),  .r111_in(8'h0),
        .valid_out(valid_out), .y0_out(y0_out), .y1_out(y1_out)
    );

    reg [127:0] h_pt  [0:99];
    reg [127:0] h_key [0:99];

    initial begin
        if (!$value$plusargs("N=%d", N_VECTORS)) N_VECTORS = 5;
        $readmemh("sim/round10_pt.txt",  h_pt);
        $readmemh("sim/round10_key.txt", h_key);
    end

    integer n;
    initial begin
        #1;
        valid_in = 1'b0;
        x0_in    = 128'h0; x1_in    = 128'h0;
        rk0_in   = 128'h0; rk1_in   = 128'h0;
        rst_n    = 1'b0;
        repeat (4) @(posedge clk);
        rst_n    = 1'b1;
        @(posedge clk);

        // Smoke test: present a few plaintexts and watch the
        // valid_out signal pulse 17 cycles after each input (the
        // y0/y1 data outputs follow 2 cycles later, at 19).
        for (n = 0; n < N_VECTORS; n = n + 1) begin : VEC_LOOP
            x0_in  = h_pt[n];
            x1_in  = 128'h0;
            rk0_in = h_key[n];
            rk1_in = 128'h0;
            @(posedge clk);
            valid_in = 1'b1;
            @(posedge clk);
            valid_in = 1'b0;
            repeat (23) @(posedge clk);
            $display("vec %0d: valid_out=%b y0_out=%032h y1_out=%032h",
                     n, valid_out, y0_out, y1_out);
        end
        $display("tb_aes_10rounds: %0d vectors, skeleton only (round 1 wired)",
                 N_VECTORS);
        $finish;
    end

endmodule

`endif
