#!/usr/bin/env python3
"""
gen_masked_aes_round1_d2.py
============================
Generate `masked_aes_round1_second_order.v` — the second-order (d=2,
share count = 3) full-chip masked AES-128 round-1 module.

Same structure as the d=1 module (SubBytes + ShiftRows + MixColumns +
AddRoundKey) but with three input/output shares and 16 instances of
`masked_sbox_second_order` (63 mask bytes per S-box = 1008 total).

Used by:
  - `syn/do_synth_d2.ys` (Yosys synthesis flow)
  - `AREA_REPORT.md` (full-chip d=2 row)
"""
import os
import sys


HEADER = """\
// =====================================================================
// masked_aes_round1_second_order.v
// =====================================================================
// Single-round masked AES-128 (Boolean masking, d=2, share count = 3).
// Generated by gen_masked_aes_round1_d2.py; do not edit by hand.
//
// Round 1 = SubBytes + ShiftRows + MixColumns + AddRoundKey.
//   - SubBytes: 16 parallel masked_sbox_second_order instances
//   - ShiftRows, MixColumns: combinational share-wise (linear GF(2^8))
//   - AddRoundKey, output register: clocked
//
// AES state packing: 128-bit bus, byte index = row + 4*col (column-major).
//   Byte 0 is (row 0, col 0), byte 4 is (row 0, col 1), ..., byte 15
//   is (row 3, col 3).
//
// Key schedule is performed OFF-LINE; the round key is supplied as
// three shares (rk0, rk1, rk2) where rk0 ^ rk1 ^ rk2 = the actual
// round key.
//
// Latency: 10 cycles (S-box pipeline) + 1 (ARK register) +
//          1 (output register) = 12 cycles.  valid_out is
//          combinational from sb_v_all.
//
// Randomness budget per round: 16 S-boxes * 63 bytes = 1008 bytes
//                              = 8064 fresh bits per AES round.
// =====================================================================

`timescale 1ns/1ps

module masked_aes_round1_second_order (
    input              clk,
    input              rst_n,
    input              valid_in,

    // ----- 16-byte plaintext (three shares) -----
    input  [127:0]     x0_in,
    input  [127:0]     x1_in,
    input  [127:0]     x2_in,

    // ----- 16-byte round key (three shares) -----
    input  [127:0]     rk0_in,
    input  [127:0]     rk1_in,
    input  [127:0]     rk2_in,

    // ----- 1008 mask bytes (16 S-boxes * 63 bytes each) -----
"""


def gen_mask_port_block():
    """Generate 1008 input ports r000_in..r1007_in, 8 per line.

    The final port row gets a trailing comma (the output port list
    follows it on the next line).
    """
    lines = []
    for i in range(0, 1008, 8):
        names = ", ".join(f"r{j:03d}_in" for j in range(i, i + 8))
        lines.append(f"    input  [7:0] {names},")
    return "\n".join(lines) + "\n"


# ShiftRows map: src_byte -> dst_byte (column-major, row r rotated left by r)
SHIFT_ROWS_MAP = [
    0, 13, 10, 7,
    4, 1, 14, 11,
    8, 5, 2, 15,
    12, 9, 6, 3,
]


def gen_shift_rows(suffix: str) -> str:
    """Generate ShiftRows assignment for one share (y0/y1/y2)."""
    lines = [f"    wire [127:0] sr_state_{suffix};"]
    for dst, src in enumerate(SHIFT_ROWS_MAP):
        lines.append(
            f"    assign sr_state_{suffix}[{dst:>2d} +: 8] = "
            f"sb_state_{suffix}[{src:>2d} +: 8];"
        )
    return "\n".join(lines) + "\n"


def gen_mix_columns(suffix: str) -> str:
    """Generate MixColumns for one share.  Standard AES matrix."""
    out = [f"    wire [127:0] mc_state_{suffix};"]
    # For each column c in 0..3 (bytes 4c..4c+3)
    # mc[0] = 2*a0 + 3*a1 + a2 + a3 = xtime(a0) ^ (xtime(a1) ^ a1) ^ a2 ^ a3
    # mc[1] = a0 + 2*a1 + 3*a2 + a3
    # mc[2] = a0 + a1 + 2*a2 + 3*a3
    # mc[3] = 3*a0 + a1 + a2 + 2*a3 = (xtime(a0) ^ a0) ^ a1 ^ a2 ^ xtime(a3)
    for c in range(4):
        b0 = 4 * c
        b1 = 4 * c + 1
        b2 = 4 * c + 2
        b3 = 4 * c + 3
        s = "sr_state_" + suffix
        out.append(
            f"    assign mc_state_{suffix}[{b0:>2d} +: 8] = "
            f"xtime_f({s}[{b0:>2d} +: 8]) "
            f"^ (xtime_f({s}[{b1:>2d} +: 8]) ^ {s}[{b1:>2d} +: 8]) "
            f"^ {s}[{b2:>2d} +: 8] ^ {s}[{b3:>2d} +: 8];"
        )
        out.append(
            f"    assign mc_state_{suffix}[{b1:>2d} +: 8] = "
            f"{s}[{b0:>2d} +: 8] ^ xtime_f({s}[{b1:>2d} +: 8]) "
            f"^ (xtime_f({s}[{b2:>2d} +: 8]) ^ {s}[{b2:>2d} +: 8]) "
            f"^ {s}[{b3:>2d} +: 8];"
        )
        out.append(
            f"    assign mc_state_{suffix}[{b2:>2d} +: 8] = "
            f"{s}[{b0:>2d} +: 8] ^ {s}[{b1:>2d} +: 8] "
            f"^ xtime_f({s}[{b2:>2d} +: 8]) "
            f"^ (xtime_f({s}[{b3:>2d} +: 8]) ^ {s}[{b3:>2d} +: 8]);"
        )
        out.append(
            f"    assign mc_state_{suffix}[{b3:>2d} +: 8] = "
            f"(xtime_f({s}[{b0:>2d} +: 8]) ^ {s}[{b0:>2d} +: 8]) "
            f"^ {s}[{b1:>2d} +: 8] ^ {s}[{b2:>2d} +: 8] "
            f"^ xtime_f({s}[{b3:>2d} +: 8]);"
        )
    return "\n".join(out) + "\n"


# sbox_second_order has ports: r00..r62 (63 bytes)
# sbox_first_order had r0_in..r27_in (28 bytes)
# d=2 S-box mapping: rNN (NN = 0..62)
# We pack 16 S-boxes × 63 = 1008 bytes in our round1 module's r000..r1007
# Each S-box i uses bytes [63*i, 63*i+63)
SBOX_MASK_COUNT = 63  # bytes per second-order S-box


def gen_sbox_instance(i: int) -> str:
    """Generate one masked_sbox_second_order instance, byte i.

    Mask bytes r000_in..r1007_in are mapped to S-box internal
    ports r00..r62 by direct offset.  Each instance is terminated
    with a comma (it's a chained declaration, no leading keyword).
    """
    base = i * SBOX_MASK_COUNT
    pn = [f"r{j:03d}_in" for j in range(base, base + SBOX_MASK_COUNT)]
    rmap = ", ".join(f".r{j:02d}({pn[j]})"
                     for j in range(SBOX_MASK_COUNT))
    bit_lo = i * 8
    name = f"u_sbox_{i}"
    return (
        f"    masked_sbox_second_order {name} (\n"
        f"        .clk(clk), .rst_n(rst_n), .valid_in(valid_in),\n"
        f"        .x0_in(x0_in[{bit_lo:>3d} +: 8]), "
        f".x1_in(x1_in[{bit_lo:>3d} +: 8]), "
        f".x2_in(x2_in[{bit_lo:>3d} +: 8]),\n"
        f"        {rmap},\n"
        f"        .valid_out(sb_v[{i:>2d}]), "
        f".y0_out(sb_y0[{i:>2d}]), .y1_out(sb_y1[{i:>2d}]), "
        f".y2_out(sb_y2[{i:>2d}]));"
    )


def gen_output_block() -> str:
    return """\
    // ----------------------------------------------------------------
    // STAGE 4: AddRoundKey (clocked register, share-wise XOR)
    // ----------------------------------------------------------------
    reg [127:0] ark_state_y0;
    reg [127:0] ark_state_y1;
    reg [127:0] ark_state_y2;

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            ark_state_y0 <= 128'h0;
            ark_state_y1 <= 128'h0;
            ark_state_y2 <= 128'h0;
        end else begin
            ark_state_y0 <= mc_state_y0 ^ rk0_in;
            ark_state_y1 <= mc_state_y1 ^ rk1_in;
            ark_state_y2 <= mc_state_y2 ^ rk2_in;
        end
    end

    // ----------------------------------------------------------------
    // STAGE 5: output register
    // ----------------------------------------------------------------
    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            y0_out <= 128'h0;
            y1_out <= 128'h0;
            y2_out <= 128'h0;
        end else begin
            y0_out <= ark_state_y0;
            y1_out <= ark_state_y1;
            y2_out <= ark_state_y2;
        end
    end

    // valid_out: combinational from sb_v_all.  12-cycle data
    // latency = 10 (S-box pipeline) + 1 (ARK) + 1 (output register).
    assign valid_out = sb_v_all;

endmodule
"""


def main(out: str = "rtl/masked_aes_round1_second_order.v"):
    parts = [HEADER, gen_mask_port_block()]
    # Output port block
    parts.append("""\
    // ----- Output -----
    output             valid_out,
    output reg [127:0] y0_out,
    output reg [127:0] y1_out,
    output reg [127:0] y2_out
);

    // ----------------------------------------------------------------
    // xtime (forward declaration so ShiftRows/MixColumns below can use it)
    // ----------------------------------------------------------------
    function [7:0] xtime_f;
        input [7:0] b;
        reg [7:0] t;
        begin
            t = {b[6:0], 1'b0};
            xtime_f = b[7] ? (t ^ 8'h1b) : t;
        end
    endfunction
""")
    # SubBytes scaffolding
    parts.append("""
    // ----------------------------------------------------------------
    // STAGE 1: SubBytes (16 parallel masked S-boxes)
    // ----------------------------------------------------------------
    wire        sb_v   [0:15];
    wire [7:0]  sb_y0  [0:15];
    wire [7:0]  sb_y1  [0:15];
    wire [7:0]  sb_y2  [0:15];

    // Pack S-box outputs into 128-bit buses.  sb_y{k}[i] holds the
    // S-box output share k for state byte i, placed at bit-slice
    // [8*i+:8].
""")
    for sfx in ("y0", "y1", "y2"):
        parts.append(
            f"    wire [127:0] sb_state_{sfx} = "
            "{" + ", ".join(f"sb_{sfx}[{i:>2d}]" for i in range(15, -1, -1)) + "};\n"
        )

    # 16 S-box instances
    parts.append("\n")
    for i in range(16):
        parts.append(gen_sbox_instance(i) + "\n")

    # sb_v_all
    parts.append("""
    wire sb_v_all = """ + " & ".join(f"sb_v[{i:>2d}]" for i in range(16)) + """;
""")

    # ShiftRows + MixColumns (per share)
    for sfx in ("y0", "y1", "y2"):
        parts.append("\n    // ---- Share " + sfx + " ----\n")
        parts.append(gen_shift_rows(sfx))
        parts.append(gen_mix_columns(sfx))

    # Output block (AddRoundKey + output register)
    parts.append(gen_output_block())

    content = "".join(parts)
    with open(out, "w") as f:
        f.write(content)
    print(f"Wrote {out} ({len(content.splitlines())} lines, "
          f"{len(content)} bytes)")


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1
         else "rtl/masked_aes_round1_second_order.v")
